### ISSUE TITLE
GetCreditCardVendor method does not work as expected

### ISSUE THREAD

**Issue by intrueder** [dekartlv/CreditCardValidation#1]
Pass `343434343434343` as an argument
Expected result: "American Express"
Actual result: "Amex"

**Comment by dekartlv** [comment]
Actually Amex == American Express
Now output will show "American_Express"
@intrueder let me know is it OK.
Thanks in advance!

**Comment by intrueder** [comment]
Just wanted to check if you will fix this issue by adding method `GetDisplayName` as here https://github.com/card-io/card.io-Android-source/blob/master/card.io/src/main/java/io/card/payment/CardType.java

It is preferable for user to see name without underscores. You can replace it with space, or remove underscore at all.

**Comment by dekartlv** [comment]
As I'm not familiar with localizations for now - just removed undescore.
